spring:
  application:
    name: openapi-creator-studio
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi/studio-api.yaml

logging:
  level:
    root: INFO
    ru.luttsev.studio: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId}] [%thread] %logger{35} - %msg%n"
